### ISSUE TITLE
Add description to README.md

### ISSUE THREAD

**Issue by davelab6** [Gue3bara/El-Messiri#1]
Please add a few paragraphs of description about the design to the README :)

**Comment by davelab6** [comment]
@Gue3bara This is now urgent :)

**Comment by davelab6** [comment]
@Gue3bara ping

**Comment by davelab6** [comment]
@Gue3bara this is the key thing for me to proceed, the other instances can be updated later

**Comment by Gue3bara** [comment]
I got busy working on the other edits as you been following up with me 
tonight i will update it
@davelab6

**Comment by Gue3bara** [comment]
I got busy working on the other edits as you been following up with me 
tonight i will update it
@davelab6

**Comment by Gue3bara** [comment]
I got busy working on the other edits as you been following up with me 
tonight i will update it
@davelab6

**Comment by Gue3bara** [comment]
updated the readme and will edit develop it further once I'm done with the final edits and checks to the font after interpolating the remaining weights

**Comment by davelab6** [comment]
@Gue3bara can be closed?

**Comment by Gue3bara** [comment]
@davelab6 can be closed but i will sill edit the read me i need to explain the naming of the type family too
