### ISSUE TITLE
U+0658 ARABIC MARK NOON GHUNNA does not look right

### ISSUE THREAD

**Issue by khaledhosny** [Gue3bara/El-Messiri#15]
The current glyph looks like a small lam, however it should be crescent-like, compare El Messiri glyph with Amiri and Noto Naskh Arabic glyphs (ignore the dotted circle):
![messiri](https://user-images.githubusercontent.com/93914/34458288-f7faff16-edd4-11e7-9a3a-5999c3330da7.png) ![amiri](https://user-images.githubusercontent.com/93914/34458246-8da977e2-edd3-11e7-89a7-f878a12fea76.png)![noto](https://user-images.githubusercontent.com/93914/34458257-e597580c-edd3-11e7-8d78-f2a0ce55feea.png)

**Comment by Gue3bara** [comment]
<img width="562" alt="screenshot 2018-01-02 23 26 08" src="https://user-images.githubusercontent.com/12478169/34500708-8a977df4-f014-11e7-810e-9e50d23c2546.png">
Updated the design according to [the conversation we had over the noon ghunna in Cairo](https://github.com/Gue3bara/Cairo/issues/22#issue-285232519)

**Comment by khaledhosny** [comment]
Looks good, thanks.
