### ISSUE TITLE
Add Medium and SemiBold instances?

### ISSUE THREAD

**Issue by davelab6** [Gue3bara/El-Messiri#2]
Since there is a 400 and 700 master, why not add Medium and SemiBold instances?

www.impallari.com/familysteps/ helps to calculate their values

**Comment by davelab6** [comment]
@Gue3bara any progress on this? :)

**Comment by Gue3bara** [comment]
This will be done after finishing the interpolation of CAIRO

**Comment by davelab6** [comment]
@Gue3bara ping

**Comment by davelab6** [comment]
@Gue3bara ping

**Comment by Gue3bara** [comment]
working on it
and i have trouble connecting to github from ADSL & 3G working on fixing it
and will sync ASAP
I expect to be done with it by the end of this weekend

On Mon, Mar 21, 2016 at 7:49 PM, Dave Crossland notifications@github.com
wrote:

> @Gue3bara https://github.com/Gue3bara ping
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Gue3bara/El-Messiri/issues/2#issuecomment-199399656

## 

Mohamed Gaber | محمد جابر
http://portfolio.gaberism.net/
MN: +20 100 332 4822 | Blog: www.gaberism.net
Skype: che.guebara | Twitter: @Gue3bara http://twitter.com/Gue3bara
