### ISSUE TITLE
Interpolation errors

### ISSUE THREAD

**Issue by davelab6** [Gue3bara/El-Messiri#3]
Numbers are not right:

<img width="722" alt="screen shot 2016-03-30 at 16 22 42" src="https://cloud.githubusercontent.com/assets/261579/14287803/43e8b136-fb22-11e5-80ca-0b6adad33e57.png">
<img width="726" alt="screen shot 2016-03-30 at 16 22 47" src="https://cloud.githubusercontent.com/assets/261579/14287804/43ecaa0c-fb22-11e5-8f45-2f6583dd0a41.png">

**Comment by Gue3bara** [comment]
@davelab6 i dont get what you mean by "numbers arent right" but i still didnt update the current version but I'm working on some fixations and redesign for some glyphs

**Comment by davelab6** [comment]
See the 0 in the first image

**Comment by Gue3bara** [comment]
@davelab6 ah that's weird!
will take care of that along with other issues

**Comment by Gue3bara** [comment]
@davelab6 fixed it was just path direction issue
