### ISSUE TITLE
Florin is missing outline

### ISSUE THREAD

**Issue by m4rc1e** [Gue3bara/El-Messiri#8]
![screen shot 2017-08-04 at 10 32 01](https://user-images.githubusercontent.com/7525512/28963226-4dfa4736-7900-11e7-91e0-c5d57acb958a.png)

I'll continue mastering in the mean time.

**Comment by Gue3bara** [comment]
<img width="390" alt="screenshot 2017-08-04 15 42 03" src="https://user-images.githubusercontent.com/12478169/28971213-7b827e6e-792b-11e7-9115-20368992a935.png">
Fixed
